#!/bin/bash
awk '
BEGIN { in_footer = 0 }
/^\s*<footer/ {
    in_footer = 1
    print "      <footer className=\"border-t border-gray-900 bg-[#0a0a0f] text-gray-400 py-16\">"
    print "        <div className=\"container mx-auto px-6\">"
    print "          <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-12 mb-16\">"
    print "            "
    print "            {/* Brand & Contact */}"
    print "            <div className=\"space-y-6\">"
    print "              <div className=\"flex items-center gap-3 mb-6\">"
    print "                <Logo size={32} className=\"text-white\" />"
    print "                <span className=\"text-2xl font-black text-white tracking-tight\">BillCraft</span>"
    print "              </div>"
    print "              "
    print "              <div className=\"space-y-4\">"
    print "                <div className=\"flex items-start gap-3\">"
    print "                  <Phone className=\"w-5 h-5 text-gray-500 mt-0.5\" />"
    print "                  <span className=\"text-sm font-medium\">Call: +91 9824194869</span>"
    print "                </div>"
    print "                <div className=\"flex items-start gap-3\">"
    print "                  <Mail className=\"w-5 h-5 text-gray-500 mt-0.5\" />"
    print "                  <span className=\"text-sm font-medium\">Email: nomanshaikh1999@gmail.com</span>"
    print "                </div>"
    print "                <div className=\"flex items-start gap-3\">"
    print "                  <MapPin className=\"w-5 h-5 text-gray-500 mt-0.5\" />"
    print "                  <span className=\"text-sm font-medium leading-relaxed\">Patan Gujarat India</span>"
    print "                </div>"
    print "              </div>"
    print ""
    print "              {/* Social Icons */}"
    print "              <div className=\"flex items-center gap-4 pt-4\">"
    print "                <a href=\"#\" aria-label=\"Facebook\" className=\"w-8 h-8 rounded bg-gray-800 flex items-center justify-center hover:bg-teal-600 hover:text-white transition-colors\">"
    print "                  <Facebook className=\"w-4 h-4\" />"
    print "                </a>"
    print "                <a href=\"#\" aria-label=\"Twitter\" className=\"w-8 h-8 rounded bg-gray-800 flex items-center justify-center hover:bg-teal-600 hover:text-white transition-colors\">"
    print "                  <Twitter className=\"w-4 h-4\" />"
    print "                </a>"
    print "                <a href=\"#\" aria-label=\"Instagram\" className=\"w-8 h-8 rounded bg-gray-800 flex items-center justify-center hover:bg-teal-600 hover:text-white transition-colors\">"
    print "                  <Instagram className=\"w-4 h-4\" />"
    print "                </a>"
    print "                <a href=\"#\" aria-label=\"LinkedIn\" className=\"w-8 h-8 rounded bg-gray-800 flex items-center justify-center hover:bg-teal-600 hover:text-white transition-colors\">"
    print "                  <Linkedin className=\"w-4 h-4\" />"
    print "                </a>"
    print "              </div>"
    print "            </div>"
    print ""
    print "            {/* Quick Links 1 */}"
    print "            <div className=\"space-y-6\">"
    print "              <h3 className=\"text-white text-lg font-bold mb-4\">Quick Links</h3>"
    print "              <ul className=\"space-y-3\">"
    print "                <li><a href=\"#\" onClick={(e) => { e.preventDefault(); window.scrollTo(0,0); }} className=\"text-sm hover:text-white transition-colors\">Home</a></li>"
    print "                <li><a href=\"#\" className=\"text-sm hover:text-white transition-colors\">About Us</a></li>"
    print "                <li><a href=\"#\" className=\"text-sm hover:text-white transition-colors\">Solutions</a></li>"
    print "                <li><a href=\"#\" className=\"text-sm hover:text-white transition-colors\">Contact us</a></li>"
    print "                <li><a href=\"#\" className=\"text-sm hover:text-white transition-colors\">Tally XML Converter</a></li>"
    print "                <li><a href=\"#\" className=\"text-sm hover:text-white transition-colors\">Blogs</a></li>"
    print "                <li><a href=\"#\" className=\"text-sm hover:text-white transition-colors\">Why BillCraft</a></li>"
    print "                <li><a href=\"#\" className=\"text-sm hover:text-white transition-colors\">Careers</a></li>"
    print "              </ul>"
    print "            </div>"
    print ""
    print "            {/* Quick Links 2 */}"
    print "            <div className=\"space-y-6\">"
    print "              <h3 className=\"text-[#0a0a0f] text-lg font-bold mb-4 select-none\">Tools</h3>"
    print "              <ul className=\"space-y-3 lg:mt-11\">"
    print "                <li><a href=\"#\" className=\"text-sm hover:text-white transition-colors\">Invoice Generator</a></li>"
    print "                <li><a href=\"#\" className=\"text-sm hover:text-white transition-colors\">Find GSTIN</a></li>"
    print "                <li><a href=\"#\" className=\"text-sm hover:text-white transition-colors\">HSN/SAC Finder</a></li>"
    print "                <li><a href=\"#\" className=\"text-sm hover:text-white transition-colors\">GST Calculator</a></li>"
    print "                <li><button onClick={() => navigate(\"/terms\")} className=\"text-sm hover:text-white transition-colors cursor-pointer text-left\">Privacy policy</button></li>"
    print "                <li><button onClick={() => navigate(\"/terms\")} className=\"text-sm hover:text-white transition-colors cursor-pointer text-left\">Terms & conditions</button></li>"
    print "                <li><button onClick={() => navigate(\"/terms\")} className=\"text-sm hover:text-white transition-colors cursor-pointer text-left\">Cookie Policy</button></li>"
    print "              </ul>"
    print "            </div>"
    print ""
    print "            {/* SEO Keywords Section */}"
    print "            <div className=\"space-y-6\">"
    print "               <h3 className=\"text-white text-lg font-bold mb-4\">Popular Tags</h3>"
    print "               <div className=\"flex flex-wrap gap-2\">"
    print "                 <span className=\"px-3 py-1 bg-gray-800/50 rounded border border-gray-800 text-[10px] font-bold uppercase tracking-wider hover:border-teal-500 hover:text-teal-400 transition-colors cursor-pointer\">Free GST Billing</span>"
    print "                 <span className=\"px-3 py-1 bg-gray-800/50 rounded border border-gray-800 text-[10px] font-bold uppercase tracking-wider hover:border-teal-500 hover:text-teal-400 transition-colors cursor-pointer\">Invoice Maker</span>"
    print "                 <span className=\"px-3 py-1 bg-gray-800/50 rounded border border-gray-800 text-[10px] font-bold uppercase tracking-wider hover:border-teal-500 hover:text-teal-400 transition-colors cursor-pointer\">Retail POS</span>"
    print "                 <span className=\"px-3 py-1 bg-gray-800/50 rounded border border-gray-800 text-[10px] font-bold uppercase tracking-wider hover:border-teal-500 hover:text-teal-400 transition-colors cursor-pointer\">Thermal Printing</span>"
    print "                 <span className=\"px-3 py-1 bg-gray-800/50 rounded border border-gray-800 text-[10px] font-bold uppercase tracking-wider hover:border-teal-500 hover:text-teal-400 transition-colors cursor-pointer\">Estimate Generator</span>"
    print "               </div>"
    print "            </div>"
    print ""
    print "          </div>"
    print ""
    print "          <div className=\"pt-8 border-t border-gray-800 flex flex-col md:flex-row items-center justify-between gap-4\">"
    print "             <p className=\"text-xs font-medium\">© 2026 BillCraft Invoicing. All rights reserved.</p>"
    print "             <div className=\"flex items-center gap-6\">"
    print "                <span className=\"text-[10px] font-bold uppercase tracking-widest text-gray-500\">Built for the modern shop owner</span>"
    print "             </div>"
    print "          </div>"
    print "        </div>"
    print "      </footer>"
    next
}
/^\s*<\/footer>/ {
    in_footer = 0
    next
}
!in_footer {
    print
}
' src/pages/LandingPage.tsx > temp.tsx && mv temp.tsx src/pages/LandingPage.tsx
